apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - name: nodejs
      port: 3001
      targetPort: nodejs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  labels:
    app: endpoint
data:
  config.js: |-
    module.exports = {
        endpoint : {
            account: "http://account-svc:8090",
            cms: "http://cms-svc:3002",
            redis: {
            port: 6379,
            host: "redis-svc",
            sentinel: false
        }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    version: v1
spec:
  selector:
    matchLabels:
      app: api
      version: v1
  replicas: 1
  template:
    metadata:
      name: api
      labels:
        app: api
        version: v1
    spec:
      containers:
        - name: api
          image: kubepia/kubetv-api:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config
              mountPath: /app/config.js
              subPath: "config.js"
          ports:
            - name: nodejs
              containerPort: 3001
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /health
              port: nodejs
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: nodejs
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: app-config
          configMap:
            name: api
            items:
              - key: config.js
                path: config.js
