apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD:k8s/deploy.yaml
  name: api
=======
  name: api-svc
>>>>>>> 68d5c559339b643b95f1786b50410734c32cd23b:k8s/k8s.yaml
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: nodejs
      port: 3001
      targetPort: nodejs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  labels:
    app: endpoint
data:
  config.js: |-
    module.exports = {
        endpoint : {
            account: "http://acc-svc:8090/",
            cms: "http://cms:3002/"
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    version: v1
spec:
  selector:
    matchLabels:
      app: api
      version: v1
  replicas: 1
  template:
    metadata:
      name: api
      labels:
        app: api
        version: v1
    spec:
      containers:
        - name: api
<<<<<<< HEAD:k8s/deploy.yaml
          image: g3.skb:8500/btv/api:latest
=======
          image: g3.skb:8500/btv/api:v1
>>>>>>> 68d5c559339b643b95f1786b50410734c32cd23b:k8s/k8s.yaml
          imagePullPolicy: Always
          volumeMounts:
          - name: app-config
            mountPath: /app/config.js
            subPath: "config.js"
          ports:
          - name: nodejs
            containerPort: 3001
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /
              port: nodejs
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: nodejs
            initialDelaySeconds: 1
            periodSeconds: 3
      volumes:
      - name: app-config
        configMap:
          name: api
          items:
          - key: config.js
            path: config.js
            
